[book]
authors = ["Lian Studer", "Enea Krähenbühl"]
language = "en"
multilingual = false
src = "src"
title = "M307 Kreditverleih - Dokumentation"

[build]
build-dir = "docs"

[output.html]

[output.pdf]
