version: '3'
services:
    webserver:
        build:
            context: ../../
            dockerfile: Dockerfile
        depends_on:
            - db
        environment:
            DATABASE_URL: ecto://m307:m307@db/m307
            SECRET_KEY_BASE: AEHwSQet/650xylvkc2r/XzOBS0HunCyRMNEVzebnlB1gUWfs80leMzKlIgioFul
            PHX_HOST: localhost
            PORT: 80
        ports:
            - 8003:80
        networks:
            - m307

    db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: m307
            MYSQL_DATABASE: m307
            MYSQL_USER: m307
            MYSQL_PASSWORD: m307
        networks:
            - m307
    
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8083:80
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: m307
            PMA_PASSWORD: m307
            PMA_ARBITRARY: 1
        networks:
            - m307

networks:
    m307:
