# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      m307_test_db:
        image: mysql
        env:
          POSTGRES_USER: m307_test
          POSTGRES_PASSWORD: m307_test
          POSTGRES_DB: m307_test
        ports:
          - 3306:3306
        
    steps:
    - uses: actions/checkout@v3
    
    - name: use node 16.15.0
      uses: actions/setup-node@v3
      with:
        node-version: 16.15.0
        
    - name: use elixir 1.13.2
      uses: erlef/setup-beam@v1
      with:
        otp-version: 24
        elixir-version: 1.13.2
    
    - name: install cypress
      run: |
        cd ./assets
        npm install
    
    - name: run cypress
      run: |
        chmod +x ./cypress-run.sh
        sh ./cypress-run.sh
