name: Deploy to Server

on:
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to Prod Server
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          scp_source: "*"
          scp_target: ~/svc/uk-m307/
          before_script: |
            mkdir -p ~/svc/uk-m307/
            cd ~/svc/uk-m307/_infra/prod/
            docker-compose down &
          after_script: |
            cd ~/svc/uk-m307/_infra/prod/ && docker-compose -p m307_prod up --build -d